---
permalink: protect-scsql/task_disaster_recovery_scsql.html 
sidebar: sidebar 
keywords:  
summary: Quando il plug-in SnapCenter per SQL Server non è disponibile, è possibile eseguire il ripristino eseguendo pochi passaggi manuali. 
---
= Disaster recovery del plug-in SnapCenter per SQL Server
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Quando il plug-in SnapCenter per SQL Server è inattivo, passare a un host SQL diverso e ripristinare i dati eseguendo pochi passaggi.

*Cosa ti serve*

* L'host secondario deve avere lo stesso sistema operativo, l'applicazione e il nome host dell'host primario.
* Trasferire il plug-in SnapCenter per SQL Server a un host alternativo utilizzando la pagina *Aggiungi host* o *Modifica host*.
+
link:https://docs.netapp.com/us-en/snapcenter/admin/concept_manage_hosts.html["Gestire gli host"]



*Fasi*

. Selezionare l'host dalla pagina *hosts* per modificare e installare il plug-in SnapCenter per SQL Server.
. (Facoltativo) sostituire il plug-in SnapCenter per i file di configurazione di SQL Server dal backup di disaster recovery (DR) al nuovo computer.
. Importare pianificazioni Windows e SQL dalla cartella del plug-in SnapCenter per SQL Server dal backup DR.


Per ulteriori informazioni, vedere il https://www.youtube.com/watch?v=_8NG-tTGy8k&list=PLdXI3bZJEw7nofM6lN44eOe4aOSoryckg["API di disaster recovery"^] video.
