---
permalink: sc-automation/rest_api_workflows_disaster_recovery_of_snapcenter_server.html 
sidebar: sidebar 
keywords:  
summary: La funzionalità di disaster recovery di SnapCenter utilizza API REST per il backup del server SnapCenter. 
---
= API REST supportata per il disaster recovery del server SnapCenter
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La funzionalità di disaster recovery (DR) di SnapCenter utilizza API REST per il backup del server SnapCenter. Utilizzando le API REST, è possibile eseguire le seguenti operazioni nella pagina REST API Swagger. Per informazioni su come accedere alla pagina Swagger, vedere link:https://docs.netapp.com/us-en/snapcenter/sc-automation/task_how%20to_access_rest_apis_using_the_swagger_api_web_page.html["Come accedere alle API REST utilizzando la pagina web delle API di swagger"].

*Cosa ti serve*

* Accedere come utente amministratore di SnapCenter.
* Il server SnapCenter deve essere attivo e in esecuzione per eseguire l'API di ripristino DR.


*A proposito di questa attività*

Il DR del server SnapCenter supporta tutti i plug-in.

[cols="10,40,50,10"]
|===
| Fase | Descrizione | API REST | Metodo HTTP 


 a| 
1
 a| 
Recuperare i backup DR del server SnapCenter esistenti


NOTE: Specificare il percorso di destinazione in cui sono memorizzati i backup di DR.
 a| 
`/4.5/disasterrecovery/server/backup?targetpath={path}`
 a| 
OTTIENI



 a| 
2
 a| 
Creare un nuovo backup DR del server.
 a| 
`/4.5/disasterrecovery/server/backup`
 a| 
POST



 a| 
3
 a| 
Ripristina un server SnapCenter da un backup DR del server specificato.

*Prerequisiti*

* Il nome host del server alternativo deve essere lo stesso del server primario, ma l'indirizzo IP può essere diverso.
* La versione del server deve essere la stessa del server primario.
* Assicurarsi che i file di backup del DR vengano copiati nel nuovo server SnapCenter utilizzando il seguente comando:
+
`xcopy <Ssource_Path> \\<Destination_Server_IP>\<Folder_Path> /O /X /E /H /K  {ex : xcopy C:\DRBackup \\10.225.81.114\c$\DRBackup /O /X /E /H /K}`



Se il plug-in non è in grado di risolvere il nome host del server, accedere a ciascun host del plug-in e aggiungere la voce etc/host per il nuovo IP nel formato:
`<New IP>	SC_Server_Name`

Ad esempio, 10.225.81.35 SCServer1

Il file server etc/host non verrà ripristinato. È possibile ripristinarlo manualmente dalla cartella di backup del DR.
 a| 
`/4.5/disasterrecovery/server/restore`
 a| 
POST



 a| 
4
 a| 
Eliminare il backup DR del server in base al nome del backup.
 a| 
``/4.5/disasterrecovery/server/backup``
 a| 
ELIMINARE



 a| 
5
 a| 
Attivare o disattivare il DR dello storage
 a| 
`/4.5/disasterrecovery/storage`
 a| 
POST

|===

NOTE: La pianificazione del backup del repository verrà ripristinata solo se si installa il plug-in SnapCenter per Windows e si collega il LUN NetApp alla macchina server.


NOTE: Se le DLL sono corrotte, provare a riparare il server SnapCenter o a correggere l'installazione errata.


NOTE: Se i file NSM o di configurazione sono corrotti, è possibile disinstallare e reinstallare il server SnapCenter con la stessa versione.

Per ulteriori informazioni, vedere il https://www.youtube.com/watch?v=_8NG-tTGy8k&list=PLdXI3bZJEw7nofM6lN44eOe4aOSoryckg["API di disaster recovery"^] video.
